var chant = function par(a){
    const ids = {
        "MARCUS VINICIUS FERREIRA DE RABELO ARRUDA": 1801,
        "ANA GABRIELA DE GOES MONTAI": 3877,
        "GABRIELA DE ALMEIDA DOMINGUES QUINTEIRO":4883,
        "CARLOS EDUARDO RIBEIRO PUGLIEZI": 5194,
        "LUCAS CAVALCANTI DIAS PEREIRA": 5967,
        "MARCELA BITTENCOURT DA SILVEIRA": 433,
        "ARIADNE FABIANE VELOSA CAVALCANTI": 7280,
        "LUCAS CAMILO ALCOVA NOGUEIRA": 484,
        "LUÍS FELIPE DE ALMEIDA PESCADA": 492,
        "ANA CRISTINA MIGUEL": 743,
        "FÁBIO LUIZ DA SILVA": 899,
        "EDUARDO DE OLIVEIRA PERES": 1753,
        "ARTHUR BARBOSA SANCHES": 1884,
        "LUANA LOPES ESCOLAR": 6909

    }
    var participante = ids[a]
    return participante;
} 

module.exports = chant;